# Generated by Django 6.0.2 on 2026-02-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_student_delete_ggg'),
    ]

    operations = [
        migrations.CreateModel(
            name='random',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('data_no', models.IntegerField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
